name: Integrate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
          # - os: windows-latest
          #   platform: win32
          #   arch: x64
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - run: sudo apt install gperf nasm
        if: ${{ matrix.platform == 'linux' }}
      - run: brew install autoconf automake libtool make gperf
        if: ${{ matrix.platform == 'darwin' }}
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          flags: --debug
      - uses: actions/upload-artifact@v7
        with:
          name: libreoffice-config-log-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            build/_ports/git+bundle+libreoffice-core/**/config.log
            build/_ports/git+bundle+libreoffice-core/**/*configure*.log
          if-no-files-found: warn
        if: always()
      - run: npm test
